---
- name: Install Docker and run MariaDB container
  hosts: dockernode
  become: yes
  vars:
    ssh_port: 2222  # Define the value of ssh_port here
  tasks:
    - block:
        - name: Yum repo for Docker
          yum_repository:
            name: docker
            description: "Repo for Docker"
            file: docker_repo
            baseurl: https://download.docker.com/linux/centos/9/x86_64/stable/
            enabled: yes
            state: present
            gpgcheck: no

        - name: Install Docker package
          command: yum install -y docker-ce --nobest
          when: ansible_distribution_major_version == "9"
          register: output

        - name: Start and enable Docker service
          service:
            name: docker
            state: started
            enabled: yes

        - name: Firewall configuration for Docker
          firewalld:
            masquerade: yes
            state: enabled
            permanent: yes
            zone: public

        - name: Enable firewall for Docker port
          firewalld:
            port: "{{ item }}"
            zone: public
            permanent: yes
            state: enabled
            immediate: yes
          loop:
            - "80/tcp"
            - "443/tcp"

        - name: Reload firewall
          service:
            name: firewalld
            state: reloaded

        - name: Restart Docker service
          service:
            name: docker
            state: restarted

    - name: Pull MariaDB container image from Docker Hub
      docker_image:
        name: mariadb:latest
        source: pull

    - name: Run MariaDB container
      command: docker run -d --name mariadb_container -p 3306:3306 -p "{{ ssh_port }}:22" -e MYSQL_ROOT_PASSWORD=mysecretpassword --restart unless-stopped mariadb:latest


