---
- name: Install NTP package
  yum:
    name: chrony
    state: present
- name: Configure NTP
  lineinfile:
   path: /etc/chrony.conf
   regexp: '^server'
   line: 'server 2.centos.pool.ntp.org iburst'
- name: Start NTP service
  service:
   name: chronyd
   state: started
   enabled: yes
- name: Set Timezone
  community.general.timezone:
   name: Africa/Cairo
